name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH to server and pull latest changes
      run: |
        echo "Adding the server's fingerprint to known_hosts"
        ssh-keyscan -H 192.168.44.128 >> ~/.ssh/known_hosts

        echo "Connecting to the server and attempting to pull latest changes"
        ssh -o ConnectTimeout=60 -v automation@192.168.44.128 \
          "echo 'Checking current directory:' && pwd && \
           echo 'Listing contents of /var/www/html/test:' && ls -la /var/www/html/test && \
           echo 'Attempting to git pull with sudo...' && sudo bash -c 'cd /var/www/html/test && git pull origin main'"
