name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH to server and pull latest changes
      run: |
        ssh-keyscan -H 192.168.44.128 >> ~/.ssh/known_hosts
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=60 automation@192.168.44.128 \
          "sudo bash -c 'cd /var/www/html/test && git pull origin main'"
